export {default as RegistrationResolver} from './registration.resolver'
export {default as AdminResolver} from './admin.resolver'
export {default as ContactsResolver} from './contact.resolver'
export {default as GalleryResolver} from './gallery.resolver'
export {default as UtilitiesResolver} from './utils.resolver'
