export {default as RegistrationService} from './registration.service'
export {default as AdminService} from './admin.service'
export {default as ContactService} from './contact.service'
export {default as GalleryService} from './gallery.service'
export {default as UtilsService} from './utilities.service'
