name: Deploy
on:
  push:
    branches: [master]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Install Node. js.
        uses: bahmutov/npm-install@v1
        with:
          node-version: '16.13.1'
      - name: Install project dependencies.
        run: yarn
      - name: Run types test
        env:
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
        run: yarn types
  schema-testing:
    needs: [type-check]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Install Node. js.
        uses: bahmutov/npm-install@v1
        with:
          node-version: '16.13.1'
      - name: Install project dependencies
        run: yarn install
      - name: Testing GraphQL queries & mutations
        env:
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
          AWS_ACCESS_ID: ${{secrets.AWS_ACCESS_ID}}
          AWS_SECRET: ${{secrets.AWS_SECRET}}
          BUCKET_REGION: ${{secrets.BUCKET_REGION}}
        run: yarn test
  deploy:
    needs: [schema-testing]
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVTE_KEY }}
          passphrase: ${{ secrets.passphrase }}
          port: 22
          script: |
            cd ${{secrets.DIRECTORY}}
            sudo git pull origin master
            sudo yarn
            sudo yarn build
            sudo pm2 restart all
